server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vitasoft
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
