CREATE TABLE IF NOT EXISTS users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(200) UNIQUE NOT NULL,
    "password" VARCHAR(200)        NOT NULL,
    "role"     VARCHAR(20)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status       VARCHAR(20),
    "text"       VARCHAR(500),
    creationDate timestamp
);